<a href="https://colab.research.google.com/github/arthur-gui-22/PROJETOS_DATA_SCIENCE-/blob/CODE-HTML/data_passagens_aereas.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [58]:
import pandas as pd
import numpy as np

from sklearn.model_selection import train_test_split
from sklearn.compose import ColumnTransformer
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import StandardScaler, OneHotEncoder

from sklearn.linear_model import LinearRegression
from sklearn.ensemble import RandomForestRegressor, GradientBoostingRegressor

from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score

In [82]:
df = pd.read_csv("dataset_passagens_aereas.csv", sep=',')
df.head()

,Companhia Aérea,Cidade de Partida,Cidade de Chegada,Distância (km),Duração (h),Classe,Índice de Demanda,Preço da Passagem (R$)
0,Airline C,São Paulo,Lisboa,4612.92,7.33,Primeira Classe,1.38,2905.36
1,Airline D,Salvador,Paris,1610.93,2.97,Econômica,1.46,696.78
2,Airline A,Rio de Janeiro,Paris,5020.31,7.09,Executiva,1.38,2267.02
3,Airline D,Brasília,Nova York,2793.27,5.37,Primeira Classe,0.70,1430.19
4,Airline A,Rio de Janeiro,Nova York,755.90,0.91,Econômica,0.91,290.49

#Limpeza dos dados

In [84]:

df_clean = df.copy()
df_clean = df_clean.drop_duplicates()
df_clean = df_clean.dropna()
df_clean.head()

,Companhia Aérea,Cidade de Partida,Cidade de Chegada,Distância (km),Duração (h),Classe,Índice de Demanda,Preço da Passagem (R$)
0,Airline C,São Paulo,Lisboa,4612.92,7.33,Primeira Classe,1.38,2905.36
1,Airline D,Salvador,Paris,1610.93,2.97,Econômica,1.46,696.78
2,Airline A,Rio de Janeiro,Paris,5020.31,7.09,Executiva,1.38,2267.02
3,Airline D,Brasília,Nova York,2793.27,5.37,Primeira Classe,0.70,1430.19
4,Airline A,Rio de Janeiro,Nova York,755.90,0.91,Econômica,0.91,290.49

# Análise Exploratória

In [ ]:
df.info()

In [ ]:
df.describe()

# Valores nulos

In [ ]:
df.isnull().sum()

# Duplicados

In [ ]:
df.duplicated().sum()

#Distribuição da variável alvo

In [ ]:
import matplotlib.pyplot as plt

df["Preço da Passagem (R$)"].hist(bins=30)
plt.title("Distribuição da variável alvo")
plt.show()

# Correlação

In [ ]:
import seaborn as sns

plt.figure(figsize=(10,6))
sns.heatmap(df.corr(numeric_only=True), annot=False, cmap="coolwarm")
plt.show()

# Contagem de variáveis categóricas

In [87]:
df["Companhia Aérea"].value_counts().head()

Companhia Aérea
Airline C    45
Airline D    42
Airline B    34
Airline A    29
Name: count, dtype: int64

# Limpeza dos dados

In [ ]:
df_clean = df.copy()
df_clean = df_clean.drop_duplicates()
df_clean = df_clean.dropna()
df_clean.head()

#Divisão Treino e Teste

In [91]:
X = df_clean.drop('Preço da Passagem (R$)', axis=1)
y = df_clean['Preço da Passagem (R$)']

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)

In [89]:
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)

#Pré-Processamento

In [92]:
numeric_cols = X_train.select_dtypes(include=['int64', 'float64']).columns
categorical_cols = X_train.select_dtypes(include=['object']).columns

In [93]:
numeric_transformer = StandardScaler()
categorical_transformer = OneHotEncoder(handle_unknown='ignore')

preprocessor = ColumnTransformer(
    transformers=[
        ('num', numeric_transformer, numeric_cols),
        ('cat', categorical_transformer, categorical_cols)
    ]
)

#Treinamento do Modelo

In [ ]:
model_gb = Pipeline(steps=[
    ('preprocessor', preprocessor),
    ('regressor', GradientBoostingRegressor(random_state=42))
])

model_gb.fit(X_train, y_train)

#Avaliar

In [96]:
y_pred = model_gb.predict(X_test)

mae = mean_absolute_error(y_test, y_pred)
print(f"MAE: {mae}")

MAE: 264.8697212596495

In [97]:
rmse = np.sqrt(mean_squared_error(y_test, y_pred))
r2 = r2_score(y_test, y_pred)

print(f"RMSE: {rmse}")
print(f"R²: {r2}")

RMSE: 350.9849761942816
R²: 0.9026815994449672